nelmio_api_doc:
    documentation:
        info:
            title: API Jeux Vidéo
            description: Une API pour gérer une base de données de jeux vidéo
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)